version: 2
jobs:
  build:
    docker:
      - image: ubuntu:latest
    steps:
      - checkout
      - restore_cache:
          key: cache
      - run:
          environment:
            TARGET: x86_64-unknown-linux-gnu
          command: |
            apt update && apt install --yes curl gcc
            curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
            source $HOME/.cargo/env
            cargo build --verbose --target "$TARGET" --lib --tests
            cargo build --verbose --target "$TARGET" --lib --tests --release
            RUST_BACKTRACE=full cargo test --target "$TARGET"
            RUST_BACKTRACE=full cargo test --target "$TARGET" --release
      - save_cache:
          key: cache
          paths:
            - "~/.cargo"
            - "./target"
